name = "my-portfolio"
compatibility_date = "2026-03-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[triggers]
crons = []

[[d1_databases]]
binding = "DB"
database_name = "my-portfolio-db"
database_id = "d0564cde-5e93-4740-8512-eaf5a51a3a36"
