-- Auto-generated by scripts/generate-d1-seed.mjs

BEGIN TRANSACTION;

DELETE FROM profiles WHERE id = 1;
INSERT INTO profiles (
      id, name, headline, email, github, linkedin, location, orientation, about_intro,
      resume_url, focus_areas_json, tech_stack_json, goals_json, updated_at
    ) VALUES (
      1,
      'Trang Tuấn Anh',
      'Cybersecurity Learner | CTF Player',
      '24520131@gm.uit.edu.vn',
      'https://github.com/TrangTuanAnh',
      'https://www.linkedin.com/in/anh-trang-tu%E1%BA%A5n-40260a394/',
      'Ho Chi Minh City, Vietnam',
      'Security Research + Practical Tooling',
      'Mình tập trung vào web security, DevSecOps, ML/Dl trong Cyber Security',
      NULL,
      '["CTF writeup theo hướng tái hiện được","Phân tích hành vi hệ thống và log","Xây dựng công cụ hỗ trợ bảo mật và tự động hóa"]',
      '["Security Operations & Tools: Burp Suite, Nmap, Wireshark (Phân tích log/traffic), Metasploit, Gobuster, SQLmap","Network & Infrastructure: TCP/IP, IDS/IPS (NFStream), Linux Administration (Ubuntu/Debian), Docker (Containerization","Programming & Frameworks: Python (Backend & Scripting), FastAPI, MySQL, C++ (Network Programming), Basic Machine Learning (ứng dụng trong phát hiện mã độc/bất thường)","Platforms & Labs: TryHackMe (Jr Penetration Tester Path), PortSwigger Academy (Web Security), Hack The Box (Starting Point)","Version Control & Tools: Git/GitHub, Markdown (Documentation)"]',
      '["Hoàn thiện portfolio cùng writeup chất lượng cao","Ra mắt thêm các project cyber security phục vục cộng đồng"]',
      '2026-03-30T04:13:10.936Z'
    );

DELETE FROM site_configs WHERE id = 1;
INSERT INTO site_configs (
      id, hero_primary, hero_secondary, hero_contact, writeup_repo_root,
      theme, enable_3d_effects, hero_tilt_max, card_tilt_max, info_tilt_max, updated_at
    ) VALUES (
      1,
      '/ctf',
      '/project',
      'mailto:24520131@gm.uit.edu.vn',
      'https://github.com/TrangTuanAnh/Writeup_tier2_hackthebox',
      'light-glass-pastel',
      1,
      5.5,
      4.6,
      3.8,
      '2026-03-30T04:13:10.936Z'
    );

DELETE FROM posts;
INSERT INTO posts (
      type, slug, title, summary, content_markdown, date, featured, is_published, tags_json,
      ctf_category, ctf_event, ctf_difficulty, ctf_external_url,
      project_stack_json, project_repo, project_demo, created_at, updated_at
    ) VALUES (
      'ctf',
      'writeup-crypto-hackmd',
      'Writeup Cryptography',
      'Writeup mảng cryptography được đăng trên HackMD, tập trung vào hướng phân tích và cách giải.',
      'Writeup cryptography đầy đủ được lưu trên HackMD. Nhấn vào link để mở nội dung chi tiết.',
      '2026-03-25',
      1,
      1,
      '["cryptography","crypto","writeup","hackmd"]',
      'crypto',
      'Crypto Writeup',
      'N/A',
      'https://hackmd.io/@4UAngjUNS_qe3MPyGCYdEg/B1uCxwJ0ge',
      '[]',
      NULL,
      NULL,
      '2026-03-30T04:13:10.936Z',
      '2026-03-30T04:13:10.936Z'
    );
INSERT INTO posts (
      type, slug, title, summary, content_markdown, date, featured, is_published, tags_json,
      ctf_category, ctf_event, ctf_difficulty, ctf_external_url,
      project_stack_json, project_repo, project_demo, created_at, updated_at
    ) VALUES (
      'ctf',
      'writeup-tier2-hackthebox',
      'Writeup Tier 2 Hack The Box',
      'Writeup chính thức hiện tại của mình, được lưu trên GitHub repo riêng.',
      'Writeup đầy đủ được lưu trên repo riêng. Nhấn vào link để xem full nội dung.',
      '2026-03-25',
      1,
      1,
      '["web","hackthebox","writeup","tier2"]',
      'web',
      'Hack The Box - Tier 2',
      'Tier 2',
      'https://github.com/TrangTuanAnh/Writeup_tier2_hackthebox',
      '[]',
      NULL,
      NULL,
      '2026-03-30T04:13:10.936Z',
      '2026-03-30T04:13:10.936Z'
    );
INSERT INTO posts (
      type, slug, title, summary, content_markdown, date, featured, is_published, tags_json,
      ctf_category, ctf_event, ctf_difficulty, ctf_external_url,
      project_stack_json, project_repo, project_demo, created_at, updated_at
    ) VALUES (
      'project',
      'tls-anomaly-detection-ids',
      'Hệ thống IDS phát hiện bất thường TLS',
      'Hệ thống IDS phát hiện bất thường lưu lượng TLS, hướng tới giảm cảnh báo sai và theo dõi hành vi kết nối đáng ngờ.',
      '## Mục tiêu

Dự án tập trung phát hiện hành vi bất thường trong luồng TLS để hỗ trợ cảnh báo sớm cho hệ thống giám sát mạng.

## Hướng triển khai

- Trích xuất đặc trưng từ traffic TLS
- Huấn luyện mô hình phát hiện bất thường
- Đánh giá theo precision/recall và khả năng áp dụng thực tế

## Trạng thái

Source code và tài liệu chi tiết được cập nhật trên GitHub repo.',
      '2026-03-25',
      1,
      1,
      '[]',
      NULL,
      NULL,
      NULL,
      NULL,
      '["Python","Machine Learning","Network Traffic Analysis","TLS"]',
      'https://github.com/TrangTuanAnh/tls-anomaly-detection-ids',
      NULL,
      '2026-03-30T04:13:10.936Z',
      '2026-03-30T04:13:10.936Z'
    );

COMMIT;

